name = "uptimeflare_worker"
main = "src/index.ts"
compatibility_date = "2025-04-02"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[triggers]
crons = [ "* * * * *" ]

[[durable_objects.bindings]]
name = "REMOTE_CHECKER_DO"
class_name = "RemoteChecker"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "RemoteChecker" ]

[[d1_databases]]
binding = "UPTIMEFLARE_D1"
database_name = "uptimeflare_d1"
database_id = "776c0069-e966-4782-b408-24e4abdd133e"
